import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rishi Creations",
  description: "Generated by Rishi Creations",
  charset: "utf-8",
  httpEquiv: "x-ua-compatible",
  content: "ie=edge",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <Head>
          <link rel="shortcut icon" type="image/x-icon" href="/favicon.png" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
          <link
            href="https://fonts.googleapis.com/css2?family=Flow+Circular&family=Urbanist:ital,wght@0,100..900;1,100..900&display=swap"
            rel="stylesheet"
          />
          <link rel="stylesheet" href="/bootstrap.min.css" />
          <link rel="stylesheet" href="/animation.css" />
          <link rel="stylesheet" href="/jquery-ui.css" />
          <link rel="stylesheet" href="/font-awesome.min.css" />
          <link rel="stylesheet" href="/remixicon.css" />
          <link rel="stylesheet" href="/slick.css" />
          <link rel="stylesheet" href="/owl.carousel.css" />
          <link rel="stylesheet" href="/flickity.css" />
          <link rel="stylesheet" href="/odometer.min.css" />
          <link rel="stylesheet" href="/skeletabs.css" />
          <link rel="stylesheet" href="/magnific-popup.css" />
          <link rel="stylesheet" href="/rs-layouts.css" />
          <link rel="stylesheet" href="/style.css" />
          <script src="/jquery.min.js"></script>
          <script src="/jquery-ui.min.js"></script>
          <script src="/bootstrap.min.js"></script>
          <script src="/ajax-contact.js"></script>
          <script src="/wow.min.js"></script>
          <script src="/jquery.appear.min.js"></script>
          <script src="/typer.js"></script>
          <script src="/jquery.malihu.PageScroll2id.min.js"></script>
          <script src="/jquery.marquee.min.js"></script>
          <script src="/slick.min.js"></script>
          <script src="/owl.carousel.min.js"></script>
          <script src="/flickity.pkgd.min.js"></script>
          <script src="/odometer.min.js"></script>
          <script src="/skeletabs.js"></script>
          <script src="/jquery.magnific-popup.min.js"></script>
          <script src="/interactions/gsap.min.js"></script>
          <script src="/interactions/rs-scroll-trigger.min.js"></script>
          <script src="/interactions/rs-splitText.min.js"></script>
          <script src="/interactions/rs-anim-int.js"></script>
          <script src="/main.js"></script>
        </Head>
        <body suppressHydrationWarning={true} className={inter.className}>
          {children}
        </body>
      </html>
    </>
  );
}
