import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rishi Creations",
  description: "Generated by Rishi Creations",
  charset: "utf-8",
  httpEquiv: "x-ua-compatible",
  content: "ie=edge",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <Head>
          <link
            rel="shortcut icon"
            type="image/x-icon"
            href="./assets/images/favicon.png"
          />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
          <link
            href="https://fonts.googleapis.com/css2?family=Flow+Circular&family=Urbanist:ital,wght@0,100..900;1,100..900&display=swap"
            rel="stylesheet"
          />
          <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
          <link rel="stylesheet" href="/assets/css/animation.css" />
          <link rel="stylesheet" href="/assets/css/jquery-ui.css" />
          <link rel="stylesheet" href="/assets/css/font-awesome.min.css" />
          <link rel="stylesheet" href="/assets/css/remixicon.css" />
          <link rel="stylesheet" href="/assets/css/slick.css" />
          <link rel="stylesheet" href="/assets/css/owl.carousel.css" />
          <link rel="stylesheet" href="/assets/css/flickity.css" />
          <link rel="stylesheet" href="/assets/css/odometer.min.css" />
          <link rel="stylesheet" href="/assets/css/skeletabs.css" />
          <link rel="stylesheet" href="/assets/css/magnific-popup.css" />
          <link rel="stylesheet" href="/assets/css/rs-layouts.css" />
          <link rel="stylesheet" href="/assets/css/style.css" />
          <script src="/assets/js/jquery.min.js"></script>
          <script src="/assets/js/jquery-ui.min.js"></script>
          <script src="/assets/js/bootstrap.min.js"></script>
          <script src="/assets/js/ajax-contact.js"></script>
          <script src="/assets/js/wow.min.js"></script>
          <script src="/assets/js/jquery.appear.min.js"></script>
          <script src="/assets/js/typer.js"></script>
          <script src="/assets/js/jquery.malihu.PageScroll2id.min.js"></script>
          <script src="/assets/js/jquery.marquee.min.js"></script>
          <script src="/assets/js/slick.min.js"></script>
          <script src="/assets/js/owl.carousel.min.js"></script>
          <script src="/assets/js/flickity.pkgd.min.js"></script>
          <script src="/assets/js/odometer.min.js"></script>
          <script src="/assets/js/skeletabs.js"></script>
          <script src="/assets/js/jquery.magnific-popup.min.js"></script>
          <script src="/assets/js/interactions/gsap.min.js"></script>
          <script src="/assets/js/interactions/rs-scroll-trigger.min.js"></script>
          <script src="/assets/js/interactions/rs-splitText.min.js"></script>
          <script src="/assets/js/interactions/rs-anim-int.js"></script>
          <script src="/assets/js/main.js"></script>
        </Head>
        <body suppressHydrationWarning={true} className={inter.className}>
          {children}
        </body>
      </html>
    </>
  );
}
